# This file is installed into /etc/httpd/conf.d/ via 'make httpd-conf-install'
# from the tlociu dancer2 app
# https://github.com/kgoess/tlociu

PerlSwitches -I/var/lib/tlociu/lib/perl5

# preload the app
#
PerlSetEnv DANCER_CONFDIR /var/www/tlociu
PerlSetEnv DANCER_ENVIRONMENT production
PerlSetEnv DANCER_VIEWS /var/www/tlociu/views
PerlSetEnv DANCER_ENVDIR /var/www/tlociu/environments
PerlSetEnv DANCER_PUBLIC /var/www/tlociu/public
PerlSetEnv DANCER_CONFIG_EXT yml

PerlLoadModule kg::Tlociu

<Location /tlociu>
  SetHandler perl-script
  PerlHandler Plack::Handler::Apache2
  PerlSetVar psgi_app /var/www/tlociu/app.psgi
</Location>

